UP = "up"
DOWN = "down"
LEFT = "left"
RIGHT = "right"


CELL_SIZE = (32, 29)
DEP_CASE = (58, 203)
DEP_BORDER_CASE = (DEP_CASE[0]-CELL_SIZE[0]-3, DEP_CASE[1]-CELL_SIZE[1]-2)

FIRST_CELL_X = 120
FIRST_CELL_Y = 80

